### PR TITLE
RHEL support + Improved OpenVPN

### PR DESCRIPTION
**Pull request by earsdown**
This is still a work in progress, don't merge yet.
- Missing documentation for new settings in `networkmanager::openvpn`
- `networkmanager::openvpn::user` removal not backwards-compatible

Creating the PR to start the conversation about these proposed changes and gauge whether acceptance is likely or if I should just permanently maintain a separate fork for openvpn on EL.

UPDATE:
- README now documents new settings in `networkmanager::openvpn`
- `user` parameter to `networkmanager::openvpn` re-introduced (but deprecated) to maintain backward compatibility.

I have no idea how to fix the tests, but these changes have been tested on CentOS 7 and have been running in production for almost a year.

### CODE REVIEW

**Comment by joshuabaird** [comment]
Is anyone still maintaining this module?  Are these RHEL support changes going to get merged in?

**Comment by raphink** [comment]
@joshuabaird We're still maintaining the module. This is a rather big PR and the tests don't pass. Could you have a look and make them pass, and maybe split the commits a bit?

**Comment by joshuabaird** [comment]
@raphink Sorry - I have switched to https://forge.puppet.com/crayfishx/network_config which has native support for NetworkManager already.

**Comment by raphink** [comment]
OK, good to know. I'm still wondering whether https://github.com/raphink/puppet-netcf would be a better approach...

**Pull request closed without merging**
